### PR TITLE
Add eol-last to enforce newline at end of file.

### PR DESCRIPTION
**Pull request by stevenpears-bjss**
Added eol-last rule, it ensures/fixes non-empty files end in a newline
https://eslint.org/docs/rules/eol-last

### CODE REVIEW

**Review by sdh100shaun — APPROVED** [review]

**Comment by premghinde** [comment]
Version bump required too please

**Review by AnnaDodson — APPROVED** [review]

**Review by Cavalier07 — APPROVED** [review]

**Comment by premghinde** [comment]
I would suggest that 2.0.2 is more appropriate. Either way, the lock file should be regenerated to reflect this new version also.

**Comment by stoiveyp** [comment]
I'll re-generate the lock file once I'm back on a laptop, thanks 👍 

In terms of the version it's a non-breaking functional change, so I was following SemVer with the minor - but happy to be guided by whatever policy you use to determine versioning.

**Comment by premghinde** [comment]
It's largely opinion driven, all I was doing was putting my opinion out there. From my pov, any problems from this additional rule can be fixed using --fix so can be technically resolved with no developer effort, hence my suggestion for a patch bump, but it is only a suggestion. I don't mind which way as long the lock file is in sync.

**Review by sdh100shaun — APPROVED** [review]

**Pull request merged**
